/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dosya.listeleme;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;

/**
 *
 * @author ozgur
 */
public class DosyaYöneticisi extends javax.swing.JFrame {

    /**
     * Creates new form DosyaYöneticisi
     */
    public DosyaYöneticisi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDizin = new javax.swing.JTextField();
        jComboBoxSıralama = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jRadioButtonSakliDosyalar = new javax.swing.JRadioButton();
        jRadioButtonBoyutlar = new javax.swing.JRadioButton();
        jRadioButtonDosyaSahipleri = new javax.swing.JRadioButton();
        jRadioButtonIndexler = new javax.swing.JRadioButton();
        jRadioButtonDizininBilgileri = new javax.swing.JRadioButton();
        jRadioButtonDosyaGruplari = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListListeleme = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Dizin:");

        jTextFieldDizin.setText("/");

        jComboBoxSıralama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alfabetik", "Değişim Tarihi", "Tersten" }));
        jComboBoxSıralama.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxSıralamaİtemStateChanged(evt);
            }
        });
        jComboBoxSıralama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSıralamaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton1.setText("Listele");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButtonSakliDosyalar);
        jRadioButtonSakliDosyalar.setText("Saklı Dosyalar");

        buttonGroup.add(jRadioButtonBoyutlar);
        jRadioButtonBoyutlar.setText("Boyutlar             ");
        jRadioButtonBoyutlar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBoyutlarActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButtonDosyaSahipleri);
        jRadioButtonDosyaSahipleri.setText("Dosya Sahiplerini Gösterme");

        buttonGroup.add(jRadioButtonIndexler);
        jRadioButtonIndexler.setText("İndexler");

        buttonGroup.add(jRadioButtonDizininBilgileri);
        jRadioButtonDizininBilgileri.setText("Dizinin Bilgileri");

        buttonGroup.add(jRadioButtonDosyaGruplari);
        jRadioButtonDosyaGruplari.setText("Dosya Gruplarını Gösterme");

        jScrollPane1.setViewportView(jListListeleme);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonSakliDosyalar)
                                    .addComponent(jRadioButtonIndexler))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonDizininBilgileri)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonDosyaGruplari))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonBoyutlar)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(136, 136, 136)
                                                .addComponent(jComboBoxSıralama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(jRadioButtonDosyaSahipleri))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDizin, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                        .addGap(271, 271, 271)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDizin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSıralama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSakliDosyalar)
                    .addComponent(jRadioButtonBoyutlar)
                    .addComponent(jRadioButtonDosyaSahipleri))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonIndexler)
                    .addComponent(jRadioButtonDizininBilgileri)
                    .addComponent(jRadioButtonDosyaGruplari))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSıralamaİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxSıralamaİtemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSıralamaİtemStateChanged

    private void jComboBoxSıralamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSıralamaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBoxSıralamaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dizin = jTextFieldDizin.getText();
        Runtime komut = Runtime.getRuntime();
        Process liste = null;
        String output="";
        String line;
        int pozisyon = jComboBoxSıralama.getItemCount();
        ButtonModel saklilar,boyutlar,altDizinler,dosyaSahipleri,index,kendiHakkinda,dosyaGrupları,secilen;
        
        DefaultListModel listModel = new DefaultListModel();
        
        saklilar = jRadioButtonSakliDosyalar.getModel();
        boyutlar = jRadioButtonBoyutlar.getModel();
        dosyaSahipleri = jRadioButtonDosyaSahipleri.getModel();
        index = jRadioButtonIndexler.getModel();
        kendiHakkinda = jRadioButtonDizininBilgileri.getModel();
        dosyaGrupları = jRadioButtonDosyaGruplari.getModel();
        
        secilen = buttonGroup.getSelection();
        
        if(secilen == saklilar){
            try {
                liste = komut.exec("ls -a "+siralamaTuru()+dizin);
            } catch (IOException ex) {
                Logger.getLogger(DosyaYöneticisi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(secilen == boyutlar){
            try {
                liste = komut.exec("ls -lh "+siralamaTuru()+dizin);
            } catch (IOException ex) {
                Logger.getLogger(DosyaYöneticisi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(secilen == dosyaSahipleri){
            try {
                liste = komut.exec("ls -g "+siralamaTuru()+dizin);
            } catch (IOException ex) {
                Logger.getLogger(DosyaYöneticisi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(secilen == index){
            try {
                liste = komut.exec("ls -i "+siralamaTuru()+dizin);
            } catch (IOException ex) {
                Logger.getLogger(DosyaYöneticisi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(secilen == kendiHakkinda){
            try {
                liste = komut.exec("ls -ld "+siralamaTuru()+dizin);
            } catch (IOException ex) {
                Logger.getLogger(DosyaYöneticisi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(secilen == dosyaGrupları){
            try {
                liste = komut.exec("ls -l -G "+siralamaTuru()+dizin);
            } catch (IOException ex) {
                Logger.getLogger(DosyaYöneticisi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            try {

                liste = komut.exec("ls "+siralamaTuru()+dizin);
            } catch (IOException ex) {
                Logger.getLogger(DosyaYöneticisi.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       BufferedReader input = new BufferedReader
            (new InputStreamReader(liste.getInputStream())); 
        try {
            while ((line = input.readLine()) != null) {
                listModel.addElement(line);
                //output += (line + '\n');
            }
        } catch (IOException ex) {
            Logger.getLogger(DosyaYöneticisi.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.out.println(output);
        jListListeleme.setModel(listModel);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButtonBoyutlarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBoyutlarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonBoyutlarActionPerformed
    
    public String siralamaTuru(){
        int siralama = jComboBoxSıralama.getSelectedIndex();
        String siralamaTuru = null;
        switch (siralama){
            case 0: siralamaTuru="";
                break;
            case 1: siralamaTuru="-t ";
                break;
            case 2: siralamaTuru="-r ";
                break;
            case 3: siralamaTuru="-s ";
                break;
        }
        return siralamaTuru;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DosyaYöneticisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DosyaYöneticisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DosyaYöneticisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DosyaYöneticisi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DosyaYöneticisi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxSıralama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListListeleme;
    private javax.swing.JRadioButton jRadioButtonBoyutlar;
    private javax.swing.JRadioButton jRadioButtonDizininBilgileri;
    private javax.swing.JRadioButton jRadioButtonDosyaGruplari;
    private javax.swing.JRadioButton jRadioButtonDosyaSahipleri;
    private javax.swing.JRadioButton jRadioButtonIndexler;
    private javax.swing.JRadioButton jRadioButtonSakliDosyalar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDizin;
    // End of variables declaration//GEN-END:variables
}
